# Test that plugin hashes from plugins.json (generated by nix-prefetch-git) are
# compatible with fetchgit. This catches any mismatch between the hash generation
# method and the fetch method used in plugin-resolution.nix.
{ pkgs, testLib, moduleUnderTest }:

let
  pluginsData = builtins.fromJSON (builtins.readFile ../../data/plugins.json);

  # Find a plugin by name
  findPlugin = name:
    let matches = builtins.filter (p: p.name == name) pluginsData.plugins;
    in builtins.head matches;

  # Resolve the rev the same way plugin-resolution.nix does
  pluginRev = plugin:
    let vi = plugin.version_info or {};
    in if vi ? lazyvim_version && vi.lazyvim_version != null && vi.lazyvim_version != "*" then
      vi.lazyvim_version
    else if vi ? tag && vi.tag != null then
      vi.tag
    else if vi ? latest_version && vi.latest_version != null then
      vi.latest_version
    else if vi ? commit && vi.commit != null && vi.commit != "*" then
      vi.commit
    else null;

  # Fetch a plugin using the same method as plugin-resolution.nix
  fetchPlugin = plugin:
    let
      rev = pluginRev plugin;
      sha256 = (plugin.version_info or {}).sha256 or null;
    in
      if rev != null && sha256 != null then
        pkgs.fetchgit {
          url = "https://github.com/${plugin.owner}/${plugin.repo}";
          inherit rev sha256;
          fetchSubmodules = false;
        }
      else null;

  # Pick a few core plugins with real commit hashes to verify
  testPluginNames = [
    "MunifTanjim/nui.nvim"
    "folke/flash.nvim"
    "catppuccin/nvim"
  ];

  testPlugins = map findPlugin testPluginNames;
  fetched = map fetchPlugin testPlugins;
  validFetches = builtins.filter (f: f != null) fetched;

in {
  # Verify that fetchgit succeeds with hashes from plugins.json
  test-fetchgit-hash-compatibility = pkgs.runCommand "test-fetchgit-hash-compatibility" {} ''
    echo "Verifying fetchgit hash compatibility with plugins.json hashes..."
    echo "Tested plugins: ${builtins.concatStringsSep ", " testPluginNames}"
    ${builtins.concatStringsSep "\n" (map (f: "echo 'Verified: ${f}'") validFetches)}
    count=${toString (builtins.length validFetches)}
    expected=${toString (builtins.length testPluginNames)}
    if [ "$count" -ne "$expected" ]; then
      echo "✗ fetchgit-hash-compatibility FAILED: only $count/$expected plugins fetched"
      exit 1
    fi
    echo "✓ fetchgit-hash-compatibility PASSED: $count/$expected plugins verified"
    touch $out
  '';
}
